services:
  deemix:
    container_name: Deemix
    build: .
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${DEEMIX_CONFIG_PATH}:/config"
      - "${DEEMIX_MUSIC_PATH}:/downloads"
    environment:
      DEEMIX_SERVER_PORT: "${DEEMIX_SERVER_PORT:-6595}"
      DEEMIX_HOST: "${DEEMIX_HOST:-0.0.0.0}"
      DEEMIX_SINGLE_USER: "${DEEMIX_SINGLE_USER:-true}"
      PUID: "${PUID:-0}"
      PGID: "${PGID:-0}"
      UMASK_SET: "${UMASK_SET:-022}"
